#!/bin/sh

mkdir -p opk
cp ./swanemu opk/swanemu opk/
cp ./icon.png opk/icon.png
cp ./COPYING opk/COPYING

# https://unix.stackexchange.com/questions/219268/how-to-add-new-lines-when-using-echo
print()
	case    ${IFS- } in
	(\ *)   printf  %b\\n "$*";;
	(*)     IFS=\ $IFS
	printf  %b\\n "$*"
	IFS=${IFS#?}
esac

# Create GmenuNx entry file plus other things

print '[Desktop Entry]
Type=Application
Name=SwanEmu
Comment=Wonderswan emulator
Exec=swanemu %f
Icon=icon
Terminal=false
Type=Application
Categories=emulators;
X-OD-NeedsDownscaling=false' > opk/default."$1".desktop

mksquashfs ./opk swanemu_"$1".opk -all-root -noappend -no-exports -no-xattrs

rm -r opk
